# Generated by Django 5.1.1 on 2024-09-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileconversion',
            name='converted_file_type',
        ),
    ]
