# Generated by Django 5.1.1 on 2024-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_fileconversion_original_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileconversion',
            old_name='original_file_type',
            new_name='original_file_format',
        ),
        migrations.AlterField(
            model_name='fileconversion',
            name='conversion_type',
            field=models.CharField(blank=True, choices=[('PDF', 'Converts to PDF'), ('JPG', 'Converts to  JPG'), ('PNG', 'Converts to PNG'), ('SVG', 'Converts to SVG')], max_length=10, null=True),
        ),
    ]
