# Generated by Django 5.1.1 on 2024-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_original_file_type_fileconversion_original_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileconversion',
            name='conversion_type',
            field=models.CharField(blank=True, choices=[('Converts to PDF', 'PDF'), ('Converts to  JPG', 'JPG'), ('Converts to PNG', 'PNG'), ('Converts to SVG', 'SVG')], max_length=100, null=True),
        ),
    ]
